### ISSUE TITLE
Scrolling down the home page should show you the about, beauty, gallery pages in snippets/links to the pages

### ISSUE THREAD

**Issue by andrewlew1s** [holistic-web/website-claud#10]
this is a little vague

**Comment by michaelfitzhavey** [comment]
# Todo:
- [ ] List items / media we can preview from About section
- *...*

- [ ] List items / media we can preview from Gallery section
- *...* 

- [ ] List items / media we can preview from Beauty section
- *...*

> A good rule of thumb is to only pull through data to the homepage that has the potential to change so it might be hard to think of something from About us. Doesn't have to be the most recent though setting a post / item to featured is simple enough and then we display the ones with the featured property
